version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: tsmallwood/mongodb_cluster:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet # share port 80 via load-balanced network called webnet
networks:
  webnet: