version: "3"
services:

  pmm-server:
    image: "percona/pmm-server:latest"
    container_name: pmm-server
    ports:
     - "80:80"
     - "443:443"
    environment:
     - SERVER_USER=pmm
     - SERVER_PASSWORD=pmm
    depends_on:
     - "mongod-1"

  mongod-1:
    image: mongo
    container_name: mongod-1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
    ports:
      - "27031:27031"
    volumes:
      - ./data/mongod/27031/db:/data/db
      - ./data/mongod/27031/log:/data/log
    command: mongod --port 27031

  pmm-client-mongo:
    image: "perconalab/pmm-client:latest"
    container_name: pmm_client
    environment:
     - PMM_SERVER=pmm-server:443
     - PMM_USER=pmm
     - PMM_PASSWORD=pmm
     - DB_TYPE=mongodb
     - DB_ARGS=--uri=mongodb://mongo:secret@mongod-1:27031
    depends_on:
     - "mongod-1"
     - "pmm-server"
